# -*- coding: utf-8 -*-
"""DSE_Veri_Bilimine_Giriş_Proje_Eğitimleri_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1culuWjtvvOr5vhsneoHwz3KiDFFMHeg1
"""

#Öğrenci Bilgilendirme Sistemi

"""
Öğrenciler
  Dersler -> Notlar -> Midterm -> Final
  Sınıflara Göre Ders Ortalaması
  Bölüm,
  Devamsızlık Bilgisi,
  Giriş Yılı
"""

OgrenciListesi=[]

DersListesi=[]

OgrenciNotuListesi=[]

def DersEkle(isim,dersKodu,mid1Etki,mid2Etki,finalEtki,donem):
  if len([ders for ders in DersListesi if ders["DersKodu"]==dersKodu])==0:
    id = len(DersListesi)+1
    DersListesi.append({"Id":id,"Isim":isim,"DersKodu":dersKodu,
                        "Mid1Etki":mid1Etki,"Mid2Etki":mid2Etki,
                        "FinalEtki":finalEtki,"Donem":donem})

def OgrenciNotuEkle(ogrenciNo,dersKodu,vize1=None,vize2=None,final=None):
  isFirst=False
  ogrenciNotuDictSorgu=[sozlukElemani for sozlukElemani in OgrenciNotuListesi if sozlukElemani["OgrenciNo"]==ogrenciNo and sozlukElemani["DersKodu"]==dersKodu]
  
  if len(ogrenciNotuDictSorgu)==0:
    ogrenciNotuDict={"OgrenciNo":ogrenciNo,"DersKodu":dersKodu}
    isFirst=True
  elif len(ogrenciNotuDictSorgu)>0:
    ogrenciNotuDict=ogrenciNotuDictSorgu[0]

  if vize1 is not None:
    ogrenciNotuDict["Vize1"]=vize1
    ogrenciNotuDict["Ortalama"] = OrtalamaHesapla(ogrenciNotuDict)
  if vize2 is not None:
    ogrenciNotuDict["Vize2"]=vize2
    ogrenciNotuDict["Ortalama"] = OrtalamaHesapla(ogrenciNotuDict)
  if final is not None:
    ogrenciNotuDict["Final"]=final
    ogrenciNotuDict["Ortalama"] = OrtalamaHesapla(ogrenciNotuDict)
    
  if isFirst:
     OgrenciNotuListesi.append(ogrenciNotuDict)

def OrtalamaHesapla(ogrenciNotuDictionaryParametre):
  ortalama=0
  ders=[ders for ders in DersListesi if ders["DersKodu"]==ogrenciNotuDictionaryParametre["DersKodu"]][0]
  if ders is not None:
    if "Vize1" in ogrenciNotuDictionaryParametre.keys():
      ortalama+=ders["Mid1Etki"]*ogrenciNotuDictionaryParametre["Vize1"]/100
    if "Vize2" in ogrenciNotuDictionaryParametre.keys():
      ortalama+=ders["Mid2Etki"]*ogrenciNotuDictionaryParametre["Vize2"]/100
    if "Final" in ogrenciNotuDictionaryParametre.keys():
      ortalama+=ders["FinalEtki"]*ogrenciNotuDictionaryParametre["Final"]/100

    return ortalama

#Öğrencilerimizi oluşturalım

def OgrenciEkle(adiSoyadi,ogrenciNo,sifre,dersler,bolum,devamsizlik,girisYili,donem,ogrenciNotlari):
  if len([eleman for eleman in OgrenciListesi if eleman["OgrenciNo"]==ogrenciNo])==0:
    OgrenciListesi.append({"AdiSoyadi":adiSoyadi,"OgrenciNo":ogrenciNo,
                           "Sifre":sifre,"Dersler":dersler,
                           "Bolum":bolum,
                            "Devamsizlik":devamsizlik,
                           "girisYili":girisYili,"Donem":donem,"OgrenciNotlari":ogrenciNotlari})

DersEkle("Python Programlama 1","PY101",20,30,50,1)
DersEkle("Python Programlama 2","PY102",30,35,35,2)
DersEkle("Veri Yapısı ve Algoritmalar 1","ALG301",25,35,40,5)

OgrenciEkle("Fethi Tekyaygil","1627","123",[],"Bilgisayar Mühendisliği",0,2014,2,[])
OgrenciEkle("Taha Tekyaygil","200","qwer",[],"İşletme",0,2015,1,[])

OgrenciNotuEkle("1627","PY101",vize1=70)

OgrenciNotuEkle("1627","PY101",vize2=55)

OgrenciListesi

hak=3
ogrenciNo=None
sifre=None
girisYapanOgrenci=None

while hak>0:
  ogrenciNo=input("Ogrenci no: ")
  sifre=input("Şifre: ")

  girisYapanOgrenciSorguListesi=[ogrenci for ogrenci in OgrenciListesi 
                     if ogrenci["OgrenciNo"]==ogrenciNo 
                     and ogrenci["Sifre"]==sifre]
  
  if len(girisYapanOgrenciSorguListesi)>0:
    girisYapanOgrenci=girisYapanOgrenciSorguListesi[0]

  if girisYapanOgrenci is None: 
    hak-=1
  else:
    print(f'Hoşgeldin {girisYapanOgrenci["AdiSoyadi"]}!')
    break

  if hak<=0:
    print("Çok fazla hatalı deneme yaptınız lütfen öğrenci işleriyle iletişime geçin!")
    exit()

