# -*- coding: utf-8 -*-
"""DSE_Veri_Bilimi_Eğitimi_1_Hafta.ipynb adlı not defterinin kopyası

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xG2J4heGxTl_tl-8sYPYcy_gXF1jtMnY

# Print Komutu
"""

print("DSE")

print "Hello World"

print(Hello)

"""# Yorum Satırları"""

#yorum yazıyorum

"""çoklu
yorum
yazıyorum
çünkü 
neden olmasın
fethi
kjfljkhdfşl
hgasdkhjasd
8721evıey vr oıyeıebwyşwuşıorewoışryşewyrhflewvuıyceulıyrkcewyrlk32

# Değişken Tanımlama

primitive tipler

int

string

bool
"""

int sayi=2; # c#

"""int"""

number=15
print(number)
print(type(number))

"""float"""

flNumber=15.7
print(flNumber)
print(type(flNumber))

"""her string bir karakter dizisi"""

karsilama="Merhaba"
print(karsilama)
print(type(karsilama))

#string -> str
#print(len(karsilama))

#karsilama='Merhaba'
karsilama2='34'
print(type(karsilama2))

fiyat=7.27
print(type(fiyat))

#BOOLEAN -> bool
b1=True
b2=False

print(b1)
print(b2)
print(type(b1))
print(type(b2))

dogru,yanlis,sayi=True,False,2
print(type(dogru))
dogru

karsilama

print("Merhaba isim")

print("Merhaba Fethi. Merhaba Çağrı. Merhaba Taha.")

isim="Fethi"
yas=24

karsilama="Merhaba,"

print(f'{karsilama} Fethi') #formatın f'sini yazdım

isim="Fethi"

?print()

yeniDegisken="Fethi"+"!"
print(yeniDegisken)

#print(karsilama,isim,"!",sep="") #seperator - ayraç
print(karsilama,isim+"!")

# Commented out IPython magic to ensure Python compatibility.
# %s -> string
# %d -> decimal -> int float

isim="Fethi"
yas=24

print("%s %d!" % (isim,yas))

fethi -> int
"2" -> 2

24 -> "24"
2 -> "2"
2.45 ->"2.45" 
1.932874324 ->"1.932874324"
True -> "True"

a=None
#print(f'{karsilama} Fethi')

#isim="Fethi"

#print(f'Merhabalar {isim}!')
#ayıraç seperator seperate
print(karsilama,isim+'!',sep=".")
#Merhaba Fethi !

"""# Matematiksel İşlemler"""

100+10

17.0+3

15+3.7

15+5.0

"39"+"67"

"35" + 67

4+7

4*3

"35"*3

"hello"*4

x+2

x = 11
print(type(x)) #int
print(x+2)  #13
print(x-2)  #9
print(x*2)  #22
print(x**5) #üs değerini al 1331
print(x/3)  #3
print(x//3) #3                 bölümü ondalıksız verir 
print(x%3)  #2               bölümden kalanı verir - modulo / mod

11/3 -> 3 bölüm: 2 kalan
11//3 -> 3 bölüm

isim="Fethi"
isim*2

y = 15
print(y//2)
print(y%2)

a=2
#a=a*3 = a*=3

#a=a+3 = a+=3
print(aYeni == a)


a=a**2 = a**=2


"""
z = 5

z*=3 ->15
z*=3 ->45
print(z)


"""
"""
z = z + 10
z = z * 3

z = z + 3 
z*=3
"""
"""
z=z+3
z+=3 -> z=z+3
z*=4 -> z=z*4
"""

"""
z+=1     # z= z+1 demek , z'nin eski değeri 5 iken yeni değeri 6 oldu.
z
"""

z*=2
z

z=7
z**=2
z

a=1
a

sayi=int(input("Bir sayı girin ikiye bölünsün: "))


print(f"Girdiğiniz sayının ikiye bölümü: {sayi//2}")

type("jsgsd")

sayi=int(input("Sayı girin:"))
sayi=str(sayi)
print(sayi*10)

x=17
bolum=x/2
print(type(x/2))
cevrilmisBolum=int(bolum)
print(cevrilmisBolum)
type(cevrilmisBolum)

a=str(cevrilmisBolum)
print(type(a))
print(a)

float("2")