# -*- coding: utf-8 -*-
"""DSE_Veri_Bilimi_Eğitimi_4_Hafta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bWMkcAJrZtZnJhIocAXXCqQYEr6ij4zV

# Koşullu Durumlar (If/Else)

if "koşul":


> "birşey yap"

print()
"""

sayi=int(input("Sayı girin: "))

if sayi>10:
  print("10'dan büyük")
elif sayi>5:
  print("5'ten büyük")

#Kullanıcıdan yaş alan bir uygulama
#18'den büyükse -> yAŞIN 18'den büyük
#18'den küçükse -> Yaşın 18'den küçük 
#18 -> Yaşın 18
"""
sayi=int(input("Yaşınızı girin: "))

if sayi>18:
  print("Yaşın 18'den büyük")
elif sayi<18:
  print("Yaşın 18'den küçük")
else:
  print("Sayı 18'e eşit")

"""





"""
1 =True
0 = False
1 and 1 = 1
1 and 0 = 0
0 and 1 = 0
0 and 0 = 0
"""
"""
a=2
a==2
"""
"""
if(a==1){
    print(a 1 e eşit)
}
"""
#indent - boşluk


"""
İkisi de aynı anda doğru olmak zorunda mı
İkisinden bir doğru olsa da olur
"""

#elif - else if 
kullaniciAdi="fethi"
sifre="123"

kullanicidanAlinanKullaniciAdi=input("Kullanıcı Adını Giriniz: ")
kullanicidanAlinanSifre=input("Şifreyi Giriniz: ")


if kullaniciAdi==kullanicidanAlinanKullaniciAdi and sifre==kullanicidanAlinanSifre:
  print("Giriş Yapıldı")
elif kullaniciAdi==kullanicidanAlinanKullaniciAdi:
  print("Şifrenizi yanlış girdiniz")
elif sifre==kullanicidanAlinanSifre:
  print("Kullanıcı adınızı yanlış girdiniz")
else:
  print("Tüm bilgileri yanlış girdiniz!")

a= int("45-5")

a=int(45.5)
a

a=int("45.2.2")
1. içerisinde nokta var mı
2. içerisinde 1 tane nokta var mı

sayiString=input("Bir sayı giriniz: ")
sayi=0
hataliMi=False

if sayiString.count(".") == 1:
  sayi=float(sayiString)
elif sayiString.count(".")==0:
  sayi=int(sayiString)
else:
  print("Hatalı sayı girişi")
  hataliMi=True



if hataliMi==False:
  if sayi>=0 and sayi<=40:
    print("Girdiğiniz sayı 0-40 arasındadır.")
  elif sayi>=41 and sayi<=70:
    print("Girdiğiniz sayı 41-70 arasındadır.")
  elif sayi>=71 and sayi<=100:
    print("Girdiğiniz sayı 71-100 arasındadır.")
  else:
    print("Sayınız aralık dışındadır.")

a=float(input("Sayi gir: "))
a

a=2

a==3

course = "PyThoN"

s = input("Lütfen bir harf giriniz: ")
 
if s.lower() in course.lower():
  print("Mevcut!")
else:
  print("Yok...")

s in [course.upper() or course.lower()] bu tarz bi şey nasıl yazılabilir?

l=list(course.lower())
l.extend(list(course.upper()))
print(l)

#s in [course.upper() or course.lower()] bu tarz bi şey nasıl yazılabilir?

course = "python"

a =list(course.lower()).extend(list(course.upper()))


s = input("Lütfen bir harf giriniz: ")


if s in list(course.upper()).extend(list(course.lower())):
  print("Mevcut!")
else:
  print("Yok...")

course = "python"

s = input("Lütfen bir harf giriniz: ")

if s not in course:
  print("Yok..")
else:
  print("Mevcut!")

#gizliSayilar=[5,7,9]
sayi = int(input("Sayı girin"))

if sayi==5:
  print("Küçük sayıyı girdiniz")
elif sayi==7:
  print("Ortanca sayıyı girdiniz")
elif sayi==9:
  print("En büyük sayıyı girdiniz")
else:
  print("Bilemediniz")

"""# While Döngü Yapısı

Koşul başlangıcı

while <koşul>:



> <doğru ifade>

> <doğru ifade>

> koşul güncelleme


Bir mantıksal şart mantıksal doğru değerine sahip olduğu sürece tekrarlanır. Döngünün sona ermesi için o şartın yanlış duruma gelmesi gerekir.Bunun için döngünün içinde değişkenler uygun şekilde güncellenir. 



  
"""

sifre="1234"

sifreDogruMu=False
kSifre=None
hak=3

while hak>0 and sifre!=kSifre:
  kSifre=input("Şifrenizi girin! Kalan Hak:"+str(hak)+" - ")

  if kSifre==sifre:
    #sifreDogruMu=True
    print("Şifreyi Doğru Girdiniz. Kalan hak:" + str(hak))
    break
  

  hak-=1

  if hak<=0:
    print("Şifreyi yanlış girdiniz!")

    """
if sifreDogruMu:
  print("Şifreyi Doğru Girdiniz. Kalan hak:" + str(hak))
else:
  print("Şifreyi yanlış girdiniz!")
  """

sayi=1

while sayi<=10:
  print(sayi)
  sayi+=1
print("Döngüden çıkıldı.")

"""# For Döngü Yapısı


for <tekrarlayan değer> in <sıralı dizi>:



> <doğru ifade>


Liste gibi sıralı bir nesnedeki elemanları sırayla tek tek alır ve döngü içerisinde işler.



"""



sayiler=[1,2,3,4]
0
1
2
3

i<4


for(int i=0;i<sayilar.count();i++){
    
    #number=sayilar[i]
}

sayilar=[1,21,91,44,56]

for number in sayilar:
  print(number)

for number in [2,45,60]:
  print(number)

print("*********")
for sayi in [2,45,57]:
  print(sayi)
  print("----")
  print(number)
  print("\n")

range(0,100,5)

print(list(range(5)))

0-1-2-3-4

for sayi in range(5):
  print(sayi)

for char in "Python Kursu":
  print(char)

.env
liste=Python,Kursu,2

liste.split(',')

"Python,Kursu,2".split(",")

for i in "Python Kursu 2".split():
  print(i)

list(range(0,20,5))

for i in range(0,20,5):
  if i == 5:    
    break
  print(i)
  
print("Döngü Bitti")

for i in range(0,20,5):
  if i == 5:
    continue
  print(i)

sayilar = list(range(8))

kareler = []
for i in sayilar:
  kareler.append(i**2)
print(kareler)

sayilar = list(range(8))
#list comprehension - liste döndürür #time complexity - space complexity'i düşürür
kareler = [sayi**2 for sayi in sayilar]
print(kareler)

sayilardeneme=list(range(8))

cift_kareler_deneme=[]
"""
for sayi in sayilardeneme:
  if sayi % 2 ==0:
    cift_kareler_deneme.append(sayi**2)
"""
for sayi in sayilardeneme:
  if sayi % 2 ==1:
    continue
  cift_kareler_deneme.append(sayi**2)
print(cift_kareler_deneme)

sayilar = list(range(8))

#[(yapılacak operasyon) (for döngüsü liste dönülecek) (if bir koşul var ise o koşul)]
0-1-2-3-4-5-6-7
cift_kareler = [i**2 for i in sayilar if i % 2 == 0]

tek_küpler = [i**3 for i in sayilar if i % 2 == 1]

print(cift_kareler)
print(tek_küpler)

mylist3 = [3,5,12,7,65,35,12,"Fethi"]

print(sum(mylist3))

"""###Listenin en büyük elemanını bulma"""

mylist = [3,5,12,7,65,35,"Fethi","Taha"]

myList2=["F","T"]

maxInt=None
maxStr=None


maxStr="Fethi"
i="Taha"

for i in mylist:
  if type(i) is str:
    if maxStr==None:
      maxStr = i
    else:
      if i>maxStr:
        maxStr=i
  
  if type(i) is int:
    if maxInt==None:
      maxInt = i
    else:
      if i > maxInt:
        maxInt=i

print(maxInt,maxStr)

"""###Liste elemanlarını toplama"""

print(a)

l1=list(range(0,5,2))
l2=list(range(0,11,5))
print(l1)
print(l2)

a=[]
for i in range(3): # 0,1,2
 a.append(l1[i]+l2[i])

a

sum(a)

l1+l2

sum(l1+l2)

list1 = [1,2,3]
list2 = [4,5,6]

"""
list3=list1+list2
print(list3)

list3=zip(list1,list2)
print(list(list3))

"""
"""
list3 = [a + b 
         for a,b in zip(list1,list2)]

print(list3)
"""

list1=[2,3,4]
list2=[5,6]

print(sum(list1,list2))
"""
list3=zip(list1,list2)
print(list(list3))
"""

"""##Cevap"""

sayi=int(input("Sayi gir: "))

print(sum(list(range(sayi+1)))) #sayının da listede olmasını istiyoruz

list(range(5))

array1=[32,25,45,65,76]
for(index=0 ; index<5 ; index++) 
{
    eleman=array1[index]
}

"""###Modüller

Bazı işlevleri kolaylıkla yerine getirmemizi sağlayan birtakım fonksiyonları ve nitelikleri içinde barındıran araçlardır. Barındırdığı bu fonksiyonları farklı dosyalar ve programlar içinde tekrar tekrar kullanma imkanı sağlar. Modüller sayesinde Python çok daha kullanışlı ve uygulaması kolay bir dil haline gelmiştir.

Python’da herhangi bir modülü kullanabilmek için öncelikle onu ‘içe aktarmamız’ gerekir. İçe aktarmak, bir modül içindeki fonksiyon ve nitelikleri başka bir program içinden kullanılabilir hale getirmek demektir.

**import <modül_adı>**
"""

import random as rnd

gizli = rnd.randint(1, 100)

check = False

tahmin = int(input("Bir tahmin giriniz:"))
print(gizli)

for x in range(5):
  tahmin = int(input("Bir tahmin giriniz:"))
  if tahmin == gizli:
    print("Tebrikler")
    check = True
    break
  elif tahmin < gizli:
    print("Daha büyük bir sayı giriniz!!")
  else:
    print("Daha küçük bir sayı giriniz!!")
    
if not check:
  print("Bilemediniz, belirlenen sayı: ", gizli)

for eleman in array1:
  eleman

sayi = 0

while sayi < 9:
  print("Sayının değeri:", sayi)
  sayi = sayi +1

sayi2 = 0

while sayi2 != 9:
  print("Sayının değeri:", sayi2)
  sayi2 +=2

#sonsuz döngü, infinite loop

sayi3 = int(input("Lütfen 1 ve 10 arasında bir sayı giriniz:"))

while sayi3 < 1 or sayi3 > 10 or sayi3==5:  
  print("Doğru olmayan bir değer girdiniz!!!!")
  sayi3 = int(input("Lütfen 1 ve 10 arasında bir sayı giriniz:"))
print("Tebrikler...")

"""##Bir listenin elemanlarını yazdıralım. """

t = [1,2,3,4,5,6]

i = 0
while (i < len(t)):
  #i+=1
  print(i, ". indexteki elemanı: ", t[i])
  i+=1

while True:
  a = input("Bir değer giriniz: ")
  if a == "Exit":
    break

"""## Comprehension Tekrar"""

liste=range(11)

karelerListesi=[]
for sayi in liste:
  if sayi % 2 == 0:
    karelerListesi.append(sayi**2)

karelerListesi

[sayi**2 for sayi in liste]

[sayi**2 for sayi in liste if sayi % 2 == 0]